### ISSUE TITLE
No spaces in filenames

### ISSUE THREAD

**Issue by bamtan** [kadranel/python-volafile-downloader#1]
Hi,

Thanks for creating this tool! I was wondering if you are able to solve the issue were spaces are not stored in the filenames?

For example, the file on Vola is named: `This Is A File Name.mp4`
python-volafile-downloader saves it as: `ThisIsAFileName.mp4`

I am using the latest commit (26ee441), Debian 9 (headless), Python 3.6.6

Thanks!

**Comment by kadranel** [comment]
Hey, the issue should be resolved with: https://github.com/kadranel/python-volafile-downloader/commit/dbe0fdd4dd2072e94281a403d58ee044a863d24a 

Hope this helps, otherwise please report back. 😃
