### ISSUE TITLE
Unsupported HTTP version ('HTTP/1.0')

### ISSUE THREAD

**Issue by mweinelt** [kadranel/python-volafile-downloader#3]
I try to use this tool on a room and all I get is this message:

> dropping connection to peer tcp4:137.74.42.196:443 with abort=True: Unsupported HTTP version ('HTTP/1.0')

**Comment by mweinelt** [comment]
Reported upstream at https://github.com/volafiled/python-volapi/issues/11. The error message comes from within autobahn.

**Comment by okuzlu** [comment]
I think its the api. Other script have the same issue.

**Comment by kadranel** [comment]
Have not really got around to it so far, but i will look at updating to volapi 5.15.0 in the following days. Sadly i do not currently really use the site that much, therefore i do not know if that fixes it already.

**Comment by mweinelt** [comment]
No, the upstream examples with volapi 5.15.0 lead to the same problem.

**Comment by mweinelt** [comment]
Fixed in volapi 5.16.0.
