### ISSUE TITLE
[Bug] RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by joshuajbrunner** [kadranel/python-volafile-downloader#5]
Hello there,

I'm getting the following error after the script runs for a while

```
Traceback (most recent call last):
  File "downloader.py", line 398, in <module>
    main()
  File "downloader.py", line 385, in main
    v.dl()
  File "downloader.py", line 96, in dl
    self.download_room()
  File "downloader.py", line 137, in download_room
    for f in file_list:
RuntimeError: OrderedDict mutated during iteration
```
Using Python 3.7.4

**Comment by szero** [comment]
Hey @joshuajbrunner, this was related to a bug in volapi, fixed here https://github.com/volafiled/python-volapi/commit/8d3745cc1c00713cada472f9153108534a95121f . You can try if the fix works for you by updating volapi with `pip3 install -U volapi`
