### ISSUE TITLE
Download in single folder

### ISSUE THREAD

**Issue by ghost** [kadranel/python-volafile-downloader#7]
Its possibile to download all data in the room in a single folder? not divided into folders for uploader's username

**Comment by apoapostolov** [comment]
This is solely needed. Also a popular option is by date.

**Comment by cfranklin42** [comment]
[My fork](https://github.com/cfranklin42/python-volafile-downloader) configures the download path in [config.py](https://github.com/cfranklin42/python-volafile-downloader/blob/master/config.py#L15). Set to a single folder, by date. you decide.
